package: speechandtextanalytics_settings
mainObject: SpeechTextAnalyticsSettingsResponse
operations:
  - type: read
    method: GET
    path: /api/v2/speechandtextanalytics/settings
    link: https://developer.genesys.cloud/devapps/api-explorer#get-api-v2-speechandtextanalytics-settings
  - type: update
    method: PUT
    path: /api/v2/speechandtextanalytics/settings
    link: https://developer.genesys.cloud/devapps/api-explorer#put-api-v2-speechandtextanalytics-settings
documentation: true
testFiles: true
initTest: true
goSDKVersion: 165